### ISSUE TITLE
fix: inappropriate margin used in blogs section

### ISSUE THREAD

**Issue by RakeshSangem** [dhrumishah/My-portfolio#1]
## Issue
The reference image shows that the title `my writings` does not have a sufficient margin. If we can add a suitable margin to it, it will look good.

### reference image

![Screenshot 2022-11-01 145733](https://user-images.githubusercontent.com/107752425/199203169-2078d40d-1d09-455d-a021-b45fe06c691b.png)

**Comment by dhrumishah** [comment]
do you like to work on it?

**Comment by RakeshSangem** [comment]
> would you like to work on it?

Sure!

**Comment by RakeshSangem** [comment]
Issue resolved #2
